/* DO NOT EDIT!!!
 * Autogenerated by try_perlapi.pl
 */


#include <EXTERN.h>
#include <perl.h>
#include <Python.h>

#include "try_perlapi.h"
#include "perlmodule.h"
#include "lang_lock.h"
#include "thrd_ctx.h"
int
try_array_len(AV* av)
{
    dCTXP;
    int RETVAL;
        RETVAL = av_len(av)+1;
    return RETVAL;
}

SV**
try_av_fetch(AV* av, I32 key, I32 lval)
{
    dCTXP;
    SV** RETVAL;
        RETVAL = av_fetch(av, key, lval);
    return RETVAL;
}

int
try_SvGETMAGIC(SV* sv)
{
    dCTXP;
    int RETVAL;
        SvGETMAGIC(sv);
        RETVAL = 0;
    return RETVAL;
}

int
try_SvSETMAGIC(SV* sv)
{
    dCTXP;
    int RETVAL;
        SvSETMAGIC(sv);
        RETVAL = 0;
    return RETVAL;
}

